
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitinventory
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data
  api:
    build: .
    depends_on: [db, redis]
    environment:
      NODE_ENV: development
      PORT: 3000
      BASE_URL: http://localhost:3000
      JWT_SECRET: super-secret-local-dev
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-replace-with-client-id}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-replace-with-client-secret}
      GITHUB_OAUTH_CALLBACK_URL: http://localhost:3000/oauth/github/callback
      DATABASE_URL: postgres://postgres:postgres@db:5432/gitinventory
      REDIS_URL: redis://redis:6379
    ports: ["3000:3000"]
    command: sh -c "npm ci && npm run build && node dist/scripts/migrate.js && node dist/server.js"
volumes:
  dbdata: {}
  redisdata: {}
