CREATE TABLE IF NOT EXISTS reports (
  id BIGSERIAL PRIMARY KEY,
  scan_id BIGINT REFERENCES scans(id) ON DELETE SET NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
